platform :ios, '8.0'
#use_frameworks!
target 'NativeDemo' do
    pod 'OpenWebRTC'
    pod 'OpenWebRTC-SDK', :git => 'https://github.com/EricssonResearch/openwebrtc-ios-sdk.git'
	pod 'XMPPFramework', '~> 3.6'
pod 'JSQMessagesViewController'
pod 'JSQSystemSoundPlayer', '~> 2.0'
#use_frameworks!
#pod 'xmpp-messenger-ios', '~> 1.0'
end
